ansible_python_interpreter: /usr/bin/python3
docker_install_compose: true
security_sudoers_passwordless:
  - kurtwood
  - superuser
docker_users:
  - kurtwood
  - superuser
firewall_allowed_tcp_ports:
  - "22"
  - "80"
  - "443"
otel_collector_version: "0.123.1"
otel_collector_arch: "arm64"
otel_grafana_cloud_endpoint: "https://otlp-gateway-prod-eu-west-2.grafana.net/otlp"
otel_grafana_cloud_prometheus_endpoint: "https://prometheus-prod-24-prod-eu-west-2.grafana.net/api/prom/push"
otel_grafana_cloud_prometheus_username: "2357903"
