$ANSIBLE_VAULT;1.1;AES256
38326365383761313336346335333664343938303662373831343964323232613330343164316337
6265373762623736366430383134613664646536353262660a663831343635323534393063383636
32646430646465366561376436306433623437373637623432656536353731393462303961643638
6365373132636534340a636337633762663264356165336337376235323164663532333661326338
34363061663063393133643961646365353432643437363861316164343833653338356465616438
63383862323830663166373434663231393637333339353666376533313665666635316364396630
35366335626664653136653936386634393464636366323830316237313535346163373734643561
31306439643538626163396365313064313835316437343639316337626238313964613133333232
64366139643065333361333934333736313763313665646463633533623132313566643165653236
32346232366633303764626330633335383533373931626430316531613133303536393637633061
65386231303339663331383864383262646663353733303130666232393438353333333662636365
37626461396562613033333561316464633263646665303536656532306265643164333738666161
32633439326637643533626161333433376535316532623764393363663862343234373664646637
30326632373662396362313538353633346439313930666635343739363862623061363034663462
31656232376663653362613830316434643461646262646333653831366132396433346263323538
30613930303765636633363537306232356166396239373731363264643936343961636432616435
35356237646234633762383430643037646638306433323535663731373731383336353033613664
36386161353866663665343861393361303435333130323434333961383565663135336536373636
62396531303039326461633638613537313764623835643864623363336366656531616132373363
35333763386135626364633733366165373234303533393731313039323739376565656164643366
37383638353265303461663166643130613934303464313831356265366361616665323963346164
30636165343866356263306364326635396634363330383331616232323431663762366134613839
30333139626532343635356130306138356632386332386439363234393234373766653638646437
39306563346461643066373334356536643233323138366639643864393036656532323964326239
35316134303936333536393630303430653038373538623639656133363935656635323134383931
37636133663961343662653535666462366539643830343634636630303838313566663030363262
35636265666336616534646365626434626564363461383465633535323930393235393237386362
63376566383037323930336437356163643565323934616638316463613033303334353361393565
38326564353962386430323366623737376539663862353830303364616237666263393537353039
64646635333838313434643931383562366531373935343333363339303761326536653561633063
66313033386631666666643136343734636132373137663263303831353930393732333136346632
35356135613131303266306632353563346435316330666131303535356332623130656332313938
63613733333732656230363562393732363665636265313337626431616636326331663766353361
61653466323231616366383130663733316338306635393133303463393630646538366536363238
336235653735363062373732353235383933
