---
otel_collector_version: "0.140.1"
otel_collector_arch: "arm64"
otel_collector_deb_url: "https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/v{{ otel_collector_version }}/otelcol-contrib_{{ otel_collector_version }}_linux_{{ otel_collector_arch }}.deb"
otel_grafana_cloud_endpoint: "https://otlp-gateway-prod-eu-west-2.grafana.net/otlp"
otel_grafana_cloud_username: "{{ lookup('env', 'OTEL_GRAFANA_CLOUD_USERNAME') }}"
otel_grafana_cloud_password: "{{ lookup('env', 'OTEL_GRAFANA_CLOUD_PASSWORD') }}"
